### ISSUE TITLE
Terminal Glasses API causing rapid memory consumption

### ISSUE THREAD

**Issue by Sudocracker** [OpenMods/OpenPeripheral#241]
After running a script using the API an error pops up on the server log and the server rapidly eats up memory until the server crashes. No errors when I try it in single player. Both my computer and the server are running Java 8.

Error Gist: https://gist.github.com/Sudocracker/917c2e22651cece3284a
Code Gist: https://gist.github.com/Sudocracker/0239eb718a9cfacce50c

Running the Direwolf20 pack, version 1.3.1 with:
* ComputerCraft 1.73
* OpenModsCore 0.7.2
* OpenMods 0.7.2
* OpenPeripheralCore 1.1.1
* OpenPeripheralAddons 0.3.1
* OpenPeripheralIntegration 0.2.2

Edit: Just downloaded the server and ran it locally, the error appeared there too. So it's not just the computer I was running the server on.

**Comment by boq** [comment]
- error fixed in OpenPeripheral-Addons (next time report glasses problems there)
- memory leak not reproducible. Also, seems unrelated. I suggest using profiler (like VisualVM) to find culprit ([this](https://bukkit.org/threads/wip-analysis-of-your-server-jvm-using-visualvm.66536/) seems like nice tutorial).
