### ISSUE TITLE
Memory leak in openperipheral.interfaces.cc.providers.PeripheralProvider$3

### ISSUE THREAD

**Issue by sfPlayer1** [OpenMods/OpenPeripheral#249]
The collection "created" had a size of 118361 on FC2 with ~518 MB of retained heap space. It's a weak hash map, but the values are strong references, preventing gc.

I've checked a few entries, they seem to be only referenced by the openperipheral class.

**Comment by Vexatos** [comment]
Using the MapMaker from google common, like [this](https://github.com/CovertJaguar/Railcraft/blob/4d9c70304198833fb382fb5681f6a48c847c5d0b/src/main/java/mods/railcraft/common/carts/LinkageManager.java#L47), seems to work rather well...

**Comment by boq** [comment]
Thanks for report. This code is workaround for CC generating and discarding peripherals on most block updates. But it seems rather weird, so I'm just going to rework this whole part to decrease cost of creating peripheral instead of relying on caching.

PS. `MapMaker` is deprecated and replaced with `CacheBuilder`

**Comment by Vexatos** [comment]
Interesting, didn't know that.

**Comment by boq** [comment]
Rework done in e0d311243fd6c821db199ae9cdc9c590b50fc38e
