### ISSUE TITLE
Entity not found

### ISSUE THREAD

**Issue by arisado** [OpenMods/OpenPeripheral#263]
So first this: https://github.com/OpenMods/OpenPeripheral/issues/183

The only thing changed are a few method names.
Its still an issue (after more then 1 year wow) and i cant understand why "getPlayerByName" or "getPlayerByUUID" is putting out such an error and let the program crash instead of returning nil?

I have CC 1.7.4, OpenModsLib 0.8, OpenPeripheral Core 1.2, OpenPeripheral Addons 0.4, and Forge 10.13.4.1558 installed for Minecraft 1.7.10 and i am playing the FTB Infinity Evolved Modpack.

**Comment by boq** [comment]
This issue was fixed few days after reporting, I just forgot to close it.

Of course, such crash still may happen, if player moves out of the range between `getPlayers` and `getPlayerByName`, but this is unavoidable.

About error: well, it would be nice to do it in Lua way (`return (nil, 'error')`), but it's legacy thing. Since it worked this way since beginning, some programs may depend on it. So only thing left is `pcall`.

**Comment by arisado** [comment]
Ohh okay i see. Im not that huge lua expert and did not know pcall. Thank you for mention pcall that will help me very much (rftools had something similar with dialing device). So i think this can be closed (dont forget it :D)
