### ISSUE TITLE
No peripheral on Ender io telepad

### ISSUE THREAD

**Issue by tubs5** [OpenMods/OpenPeripheral#266]
When i wrap it as a peripheral i get one functon named hello_segfault and prints "This peripheral is broken"

http://pastebin.com/KsR3Nvvg

**Comment by boq** [comment]
This class contains field with client-only type. I can't do anything on my side..

**Comment by Vexatos** [comment]
@boq You could simply ignore exceptions like that and return null instead of a broken peripheral. I also had issues because of that and had to do [this](https://github.com/asiekierka/Computronics/blob/b8033c04d5d16ed3dfd2e399bbda6b5ead7f6d05/src/main/java/pl/asie/computronics/tile/TileEntityPeripheralBase.java#L81) to fix it...

@tubs5 for what it's worth, official EnderIO support for ComputerCraft or OpenComputers is in [Computronics](http://wiki.vex.tty.sh/wiki:computronics), not in OpenPeripheral (they both work together rather well). Telepad support will be added in the next version.

**Comment by boq** [comment]
Well, at one point I changed behaviour and allowed exception to propagate. I will see if I can restore it.

Anyway, this problem can be fixed by simple `@SideOnly`.

PS. "Official". We already had discussion about this.
